apiVersion: apps/v1
kind: Deployment
metadata:
  name: constellationprodservice
  labels:
    app: constellationprodservice
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: constellationprodservice
  template:
    metadata:
      labels:
        app: constellationprodservice
    spec:
      containers:
      - name: constellationprodservice
        image: spacexstarlink.azurecr.io/constellationprodrepo:V1.0.0.1
        ports:
        - containerPort: 8088
        resources:
          requests:
            cpu: 250m
            memory: 400Mi
          limits:
            cpu: 500m
            memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: constellationprodservice
  namespace: constellationprodnspace
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8088
    targetPort: 8088

        

